# Site Name
site_name: ZonaPonsel

# Theme
theme:
  name: material

  # Font Theme
  font:
    text: Jost

  # Features
  features:
    - toc.separate

  # Pallete
  pallete:
    primary: light blue

# Extra Features
extra:
  # Social Profile
  social:
    - icon: fontawesome/brands/github
      link: https://zonaponsel.github.io

# Markdown Extensions
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      toc_depth: 3
      permalink: true
      slugify: !!python/name:pymdownx.slugs.uslugify

# Plugins
plugins:
  - search

# Copyright
copyright: Copyright &copy; 2021 ZonaPonsel
